DROP TABLE IF EXISTS review_queue CASCADE;
DROP TABLE IF EXISTS review_stats CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS word_ai_data CASCADE;
DROP TABLE IF EXISTS words CASCADE;
DROP TABLE IF EXISTS users CASCADE;
