-- Clear all existing quiz data; new 6-level quizzes will be regenerated by the AI worker.
TRUNCATE word_quizzes;

-- Cancel pending quiz jobs (old types); they'll be re-enqueued via backfill.
UPDATE ai_pending_jobs
SET status = 'done'
WHERE job_type IN ('initial_quizzes', 'advanced_quizzes')
  AND status = 'pending';
